name: 'WikiSource Exporter'
description: 'WikiSource Exporter is a tool for exporting Wikisource documents to many formats, such as EPUB or PDF'
author: 'ruslanbay'

inputs:
  title:
    description: 'Page title (e.g. Constitution_of_the_United_States_of_America)'
    required: true
  lang:
    description: 'Language code: ru, en, de, fr, ...'
    required: true
    default: 'en'
  format:
    description: 'Output format: epub, epub-3, epub-2, htmlz, mobi, pdf, pdf-a4, pdf-a5, pdf-a6, pdf-letter, rtf, txt'
    required: true
    default: 'txt'
  nocredits:
    description: 'Do not include the credits list in the exported document'
    required: false
    default: 'true'
  nocache:
    description: 'Do not cache anything (re-fetch all data)'
    required: false
    default: 'false'

outputs:
  output-path:
    description: 'Path to the exported document'
    value: 'output'

runs:
  using: 'docker'
  image: 'docker://ghcr.io/ruslanbay/wikisource-exporter:latest'
  args:
    - ${{ inputs.title }}
    - ${{ inputs.lang }}
    - ${{ inputs.format }}
    - ${{ inputs.nocredits }}
    - ${{ inputs.nocache }}

branding:
  icon: 'book'
  color: 'blue'