name: 'WikiSource Exporter'
description: 'WikiSource Exporter is a tool for exporting Wikisource documents to many formats, such as EPUB or PDF'
author: 'ruslanbay'

inputs:
  title:
    description: 'Page title (e.g. Constitution_of_the_United_States_of_America)'
    required: true
  lang:
    description: 'Language code: ru, en, de, fr, ...'
    required: true
    default: 'en'
  format:
    description: 'Output format: txt, epub, pdf'
    required: true
    default: 'txt'
  nocredits:
    description: 'Do not include the credits list in the exported document'
    required: false
    default: 'true'
  nocache:
    description: 'Do not cache anything (re-fetch all data)'
    required: false
    default: 'false'

outputs:
  output-path:
    description: 'Path to the exported document'
    value: '/github/workspace/output'

runs:
  using: 'docker'
  image: 'docker://ghcr.io/ruslanbay/wikisource-exporter:latest'
  env:
    INPUT_TITLE: ${{ inputs.title }}
    INPUT_LANG: ${{ inputs.lang }}
    INPUT_FORMAT: ${{ inputs.format }}
    INPUT_NOCREDITS: ${{ inputs.nocredits }}
    INPUT_NOCACHE: ${{ inputs.nocache }}
  entrypoint: '/bin/sh'
  args:
    - -c
    - |
      mkdir -p /github/workspace/output && \
      php ./bin/console app:export \
        ${INPUT_NOCREDITS} == 'true' && '--nocredits' || '' \
        ${INPUT_NOCACHE} == 'true' && '--nocache' || '' \
        --lang "${INPUT_LANG}" \
        --format "${INPUT_FORMAT}" \
        --title "${INPUT_TITLE}" \
        --path "/github/workspace/output/" && \
      echo "output-path=/github/workspace/output" >> "$GITHUB_OUTPUT"

branding:
  icon: 'book'
  color: 'blue'